URL_SERVICE = "https://9d5e6965-1e4f-4e34-8055-95867a710510.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_SEARCH = "/api/v1/products/kits"
CREATE_KIT_PATH = "/api/v1/kits"